export const ADD_INGREDIENT = 'ADD_IGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_IGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
